
파욱 또야 국제 명상 센터 (삥우린)

* 목차 :TOC_2_gh:
- [[#모든-수행자를-위한-규정][모든 수행자를 위한 규정]]
- [[#입소-규칙][입소 규칙]]
- [[#숙소-및-시설-규칙][숙소 및 시설 규칙]]
- [[#공양간-규칙][공양간 규칙]]
- [[#시마-홀戒壇--명상-홀-규칙][시마 홀(戒壇) / 명상 홀 규칙]]
- [[#외출-허가-규칙][외출 허가 규칙]]
- [[#퇴소-규칙][퇴소 규칙]]
- [[#기타-일반-규칙][기타 일반 규칙]]

* 모든 수행자를 위한 규정

* 입소 규칙

(1) 파욱 또야에 도착하거나 허가를 받고 떠날 때, 빅쿠, 사미 및 남성 수행자는 승가 사무국(Sangha Office Department)에서 등록을 해야 하며, 셰얄레이(Sayalay)와 여성 수행자는 셰얄레이 사무실(Sayalay Office)에서 등록해야 합니다.
(2) 빅쿠와 사미는 닛삭기야(Nissaggiya, 포기해야 할 물건)와 아깝삐야(Akappiya, 부적절한 물건)를 완전히 포기한 후에만 본 센터에 거주할 수 있습니다.
(3) 종교 신분증(빅쿠 신분증/셰얄레이 신분증), 시민권 카드(NRC), 여권, 비자 및 기타 필요한 추천서를 해당 담당자에게 제시할 수 있어야 합니다.
(4) 해당 사무실에서 배정해 준 꾸띠(거처)에만 거주해야 합니다.
(5) 허가 없이 꾸띠에 들어가 거주하거나 꾸띠를 옮기는 것은 금지됩니다. (꾸띠를 옮기고자 할 때는 관련 담당자의 허가를 받아야 합니다.)

* 숙소 및 시설 규칙

(1) 꾸띠를 나갈 때마다 반드시 수도꼭지를 잠그고 가전제품 전원을 끄며 문을 잠가야 합니다.
(2) 개인 위생과 꾸띠 내•외부의 청결 유지에 특별히 신경 써야 합니다.
(3) 쓰레기와 음식물 찌꺼기는 반드시 지정된 쓰레기통에 버려야 합니다.
(4) 벽에 못을 박거나 테이프, 플라스터 등을 붙이는 것은 금지됩니다.
(5) 바닥이 손상되지 않도록 관리하십시오. 긁힘이나 마모를 방지하기 위해 책상과 의자의 다리를 천으로 감싸야 합니다.
(6) 가방이나 무거운 상자를 바닥에 끌지 마십시오. (해당 물품 아래에 천이나 매트를 깔아 주십시오.)
(7) 화재 예방을 위해 꾸띠 내에서 촛불이나 향을 피우는 것을 삼가하십시오. 쓰레기나 낙엽을 태우는 행위는 금지됩니다.
(8) 특정 꾸띠에 비치된 물품을 다른 꾸띠로 옮기거나 꾸띠 밖으로 반출해서는 안 됩니다.
(9) 배관/전기 수리, 지붕 누수, 흰개미 피해 등의 문제가 발생하면 해당 사무실에 알려 조치를 취해야 합니다.
(10) 새 모기장, 빨래줄, 추가 세면대 또는 수도관 등을 설치하고자 할 경우 관련 담당자와 상의하고 협력해야 합니다.
(11) 본인의 행동으로 인해 꾸띠 시설이 파손될 경우, 수리 또는 교체의 책임은 본인에게 있습니다.
(12) 아스팔트 도로변 꾸띠에 거주하는 셰얄레이와 여성 수행자는 꾸띠 정면에 빨래를 널어서는 안됩니다.
(13) 외부인을 꾸띠 내로 들여보내거나 외부인에게 심부름을 시키거나, 음식 및 물품을 나누어 주는 행위를 금지합니다.

* 공양간 규칙

(1) 질병(Gilāna)이 있는 경우를 제외하고 모두 탁발을 나가야 합니다.
(2) 목어가 울리기 전에 공양간에 도착해야 합니다.
(3) 공양간에서는 가급적 침묵을 유지하며, 보시자와 봉사자들에게 자애(Mettā)를 닦고 자신의 명상 주제에 마음을 챙겨야 합니다.
(4) 공양을 받는 동안 대화를 하거나 줄을 끼어드는 행위는 피해야 합니다.
(5) 식사를 마친 후에는 테이블과 바닥 구역을 청소해야 합니다.
(6) 발우와 식기류를 씻을 때, 부딪히는 소리가 나지 않도록 부드럽고 주의 깊게 씻어야 합니다.
(7) 대화를 하면서 식기를 씻는 행위를 피하십시오.
(8) 나야까(Nāyaka) 위원회의 허가를 받은 경우를 제외하고, 모든 공양은 공양간에서만 해야 합니다.
(9) 음식을 받을 때는 적당한 양만 가져가야 하며, 개에게 줄 목적으로 필요 이상의 음식을 가져가서는 안 됩니다.

* 시마 홀(戒壇) / 명상 홀 규칙

(1) 모든 명상 시간 정시에 도착해야 하며, 명상 시간 동안 끝까지 자리를 지켜야 합니다.
(2) 명상 중에 관절을 꺾어 소리를 내거나, 웃거나, 시끄럽게 부채질하거나, 매트를 거칠게 끌거나, 발소리를 크게 내거나, 문을 시끄럽게 여닫지 마십시오.
(3) 재채기, 헛기침, 기침이 날 경우 천으로 입을 가려 소리를 최대한 줄여야 합니다.
(4) 매일 밤 시마/명상 홀에서 열리는 법문에 빠짐없이 참석해야 합니다.
(5) 정해진 시간 외에도 명상 중인 수행자가 있을 수 있으므로, 홀 안에서 대화(또는 설법)하는 것은 엄격히 금지됩니다.
(6) 긴급 상황(화장실 이용 등)을 제외하고 명상 시간 중에 홀을 출입하지 마십시오.
(7) 명상 시간 동안 휴대폰, 시계 등 소리가 나는 모든 전자 기기는 꺼두어야 합니다.
(8) 지퍼가 달린 명상용 모기장은 절대 사용해서는 안 됩니다.
(9) 명상 시간 중에 모기장을 접거나 방충망, 창문, 커튼을 여닫지 마십시오.
(10) 명상을 마치고 숙소로 돌아갈 때는 명상용 모기장을 깔끔하게 접어서 정리해야 합니다.

* 외출 허가 규칙
(1) 외출할 타당한 사유가 있는 경우, 해당 사무실과 나야까 사야도의 허가를 받은 후에만 외출할 수 있습니다. 귀원 시에는 즉시 사무실에 보고해야 합니다.
(2) 외박을 할 경우, 숙소 열쇠를 해당 사무실에 맡겨야 합니다.
(3) 마을이나 시내에 나갈 때는 위엄 있고 평온한 태도를 유지하여 신심을 일으킬 수 있도록 해야 합니다.

* 퇴소 규칙

(1) 퇴소하기 하루 전에 해당 사무실에 알리고 퇴소 양식을 작성해야 합니다.
(2) 숙소 내외부를 청소하고 빌린 식기 및 물품을 깨끗이 씻어 정리해야 합니다.
(3) 숙소 열쇠와 대여 물품은 해당 사무실에 반납해야 합니다. (직접 기증한 꾸띠라 하더라도 열쇠는 반납해야 합니다.)
(4) 개인 소지품을 남겨두지 마십시오.

* 기타 일반 규칙

(1) 삼보(붓다, 담마, 상가)와 스승을 공경하고 존중해야 합니다.
(2) 계율을 엄격하고 정중하게 지켜야 합니다.
(3) 도반들과 인내와 자애를 바탕으로 대화하고 생활해야 합니다.
(4) 정해진 날짜와 시간에 정기적으로 명상 진도를 보고해야 합니다.
(5) 수행자들끼리 법(Dhamma)을 토론할 때 전문가가 아니면 오해가 생길 수 있으므로, 반드시 명상 스승과만 상담하십시오. 타인의 수행을 비판하지 마십시오.
(6) 명상에 빠져야 할 타당한 이유가 있다면 휴가를 신청할 수 있습니다. 허가 없이 일주일에 3회 이상 결석하는 경우 조치가 취해질 것입니다.
(7) 흡연, 코담배, 빈랑나무 열매(Betel nut)를 씹는 행위를 금합니다.
(8) 수시로 공지되는 규칙과 지시 사항을 준수해야 합니다.
(9) 경행은 경내에서만 하십시오. 걷거나 서 있을 때 지도받은 명상 주제를 유지하십시오. 정해진 좌선 시간을 모두 채운 후에만 경행을 하십시오.

파욱 또야 국제 명상 센터 (삥우린)
